/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    gpioSetup
 * Signature: (IIIJ)V
 */
JNIEXPORT void JNICALL Java_Main_gpioSetup
  (JNIEnv *, jclass, jint, jint, jint, jlong);

/*
 * Class:     Main
 * Method:    getGpioBaseAddress
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Main_getGpioBaseAddress
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    setLedColor
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_Main_setLedColor
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     Main
 * Method:    clearColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Main_clearColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     Main
 * Method:    usleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Main_usleep
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
